#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

case "$TERM" in
xterm*)
	# The following programs are known to require a Win32 Console
	# for interactive usage, therefore let's launch them through winpty
	# when run inside `mintty`.
	for name in node ipython php php5 psql python2.7 python
	do
		alias $name="winpty $name.exe"
	done
	;;
esac

# SSH with zsh
zssh() ssh "$@" -t zsh

# Add Anaconda to Path
export PATH=/c/OneDrive/Windows/System/Miniconda2:/c/OneDrive/Windows/System/Miniconda2/Scripts:$PATH

# Add Sublime to Path
export PATH=/c/OneDrive/Windows/PortableApps/SublimePortable:$PATH
